[package]
name = "tunglo"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.31", features = ["derive"] }
russh = "0.50.0"
thiserror = "2.0.11"
tokio = { version = "1.43.0", features = ["full"] }
