[storage]
type = "local" # uses a simple "known_hosts" file
# type = "rqlite"
# rqlite_host = "rqlite_host:3000"
# rqlite_user = "" # Option
# rqlite_password = "" # Option

[[tunnels]]
name = "my_web_service"
remote_ssh_address = "116.203.141.67"
remote_ssh_port = 22
remote_ssh_user = "macca"
private_key_path = "/Users/macca/.ssh/macca-macbook"
remote_interface_address = "0.0.0.0"
remote_interface_port = 9000
to_address = "localhost"
to_port = 8080
type = "http"
# [tunnels.private_key_passphrase]
# value = "plaintext_value"
# from_env = "env-var-name"
[[tunnels]]
name = "another_web_service"
remote_ssh_address = "116.203.141.67"
remote_ssh_port = 22
remote_ssh_user = "macca"
private_key_path = "/Users/macca/.ssh/macca-macbook"
remote_interface_address = "0.0.0.0"
remote_interface_port = 9001
to_address = "localhost"
to_port = 8081
type = "http"
