[storage]
type = "local" # uses a simple "known_hosts" sqlite3 file
# type = "rqlite" # uses a rqlite db (https://rqlite.io)
# [storage.rqlite]
# host.from_env = "ciao"
# password.from_env "env_var"
# user.value = "bomboclat"

[[tunnels]]
name = "my_web_service"
remote_ssh_address = "116.203.141.67"
remote_ssh_port = 22
remote_ssh_user = "macca"
private_key_path = "/Users/macca/.ssh/macca-macbook"
remote_interface_address = "0.0.0.0"
remote_interface_port = 9000
to_address = "localhost"
to_port = 8080
type = "http"
# private_key_passphrase.value = "plaintext_value"
# OR privatekey_passphrase.from_env = "env-var-name"
