tunnels:
  - name: my-web-service
    remote-ssh-address: 116.203.141.67
    remote-ssh-port: 22
    remote-ssh-user: macca
    private-key-path: /home/macca/.ssh/macca-desktop
    # private-key-passphrase: passphrase 
    # private-key-passphrase: 
    #   kubernetes-secret-name: secret-name
    #   kubernetes-secret-key: secret-key
    # private-key-passphrase:
    #   from-env: env-secret-key
    remote-interface-address: 0.0.0.0
    remote-interface-port: 9000
    to-address: 11.11.11.201
    to-port: 80
    type: http
